name: Data Update Notification

on:
  schedule:
    # Friday
    - cron: '30 6,9,12,15,18,21 * * 5'
    # Saturday
    - cron: '30 0,6,9,12,15,18,21 * * 6'
    # Sunday
    - cron: '30 0,6,9,12,15,18,21 * * 0'
    # Monday
    - cron: '30 0,6,9,12,15,18,21 * * 1'
    # Tuesday
    - cron: '30 0,6,9,12,15,18,21 * * 2'
    # Wednesday
    - cron: '30 0,6,9,12,15,18,21 * * 3'
    # Thursday
    - cron: '30 0,9,15,21 * * 4'

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for data updates
      id: check_update
      run: |
        if git diff --name-only HEAD^ HEAD | grep 'Weekly-Shiny-App/FTN_charts_2024.csv'; then
          echo "Data updated"
          echo "::set-output name=data_updated::true"
        else
          echo "No data update"
          echo "::set-output name=data_updated::false"
        fi

    - name: Send email notification
      if: steps.check_update.outputs.data_updated == 'true'
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        curl --request POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer $SENDGRID_API_KEY" \
          --header "Content-Type: application/json" \
          --data '{
            "personalizations": [{
              "to": [{"email": "Doug.Analytics87@gmail.com"}],
              "subject": "Data Update Notification"
            }],
            "from": {"email": "Doug.Analytics87@gmail.com"},
            "content": [{
              "type": "text/plain",
              "value": "Data has been updated!"
            }]
          }'
