library(tidyverse)
library(nflreadr)
library(httr)
library(jsonlite)

options(scipen = 9999)

#source("G:/My Drive/Giants/Code/ftn_functions.R")

source("ftn_functions.R")

SEASON <- 2024
key <- Sys.getenv("API_KEY")  # Use the API key from the environment variable

ftn_charts <- ftn_game_data(type = "charts", year = SEASON)
ftn_plays <- ftn_game_data(type = "plays", year = SEASON)

url <- paste0("https://data.ftndata.com/games/", SEASON)
req <- GET(url, add_headers(Authorization = key))
ftn_games <- as.data.frame(fromJSON(rawToChar(req$content)))

# Debug prints
print(names(ftn_charts))
print(names(ftn_plays))
print(names(ftn_games))

# Continue with your data processing
